### ISSUE TITLE
添加QUICK CAlCULUS功能

### ISSUE THREAD

**Issue by AresConnor** [ITCraftDevelopmentTeam/XDbot2#117]
### 描述

QUICK CALCULUS - 即：快速微积分，可以挑选一些很简单的微积分或者极限给群友做做 /狗头

### 原因

受到[QUICK MATH]的启发，另外QUICK CALCULUS可能会难一点，可以酌情选择3-5个消息内的正确答案的消息，或者比QUICK MATH获得的奖励更多，之类的

**Comment by xxtg666** [comment]
这个功能可以有，但不是现在
开发组大家都是中学生，没学过微积分，如果您特别需要的话可以 [自行提交pr](https://github.com/This-is-XiaoDeng/XDbot2/pulls)（

**Comment by montmorill** [comment]
我可以（x

**Comment by This-is-XiaoDeng** [comment]
> 我可以（x

你来（）

**Comment by This-is-XiaoDeng** [comment]
![图片](https://user-images.githubusercontent.com/104149371/230361862-b9185dc4-4c7e-4bfc-87e1-83bf154175ce.png)
看起来问题不大.jpg

**Comment by AresConnor** [comment]
6啊

**Comment by This-is-XiaoDeng** [comment]
或许可以了（？

**Comment by This-is-XiaoDeng** [comment]
感谢
