### ISSUE TITLE
[添加物品] 林檎

### ISSUE THREAD

**Issue by meowjiao321** [ITCraftDevelopmentTeam/XDbot2#143]
### 描述

该物品可以用114个VimCoin购买114个
该物品使用后会对群昵称强制加入[檎兽]前缀

### 原因

我是homo

**Comment by YifanZhuZhu** [comment]
臭死了。。。
算了吧（

**Comment by This-is-XiaoDeng** [comment]
> 臭死了。。。 算了吧（

关键是在 XDbot2 不是管理的情况下改不了群昵称（
