### ISSUE TITLE
新功能：/bank

### ISSUE THREAD

**Issue by YifanZhuZhu** [ITCraftDevelopmentTeam/XDbot2#150]
### 描述

1./su bank rate [a]:利率 a %
2./bank lend [money]:贷款 money vi
3./bank view:查看需还贷金额
4./bank repay:还贷

### 原因

因为二十面骰稳亏不赚(bushi

**Comment by YifanZhuZhu** [comment]
以防superuser抢劫，a最好设在0-50之间）

**Comment by This-is-XiaoDeng** [comment]
OK

**Comment by This-is-XiaoDeng** [comment]
> 以防superuser抢劫，a最好设在0-50之间）

彳亍（虽然还没开始做）
