### ISSUE TITLE
[优化建议] 在群聊回复XDbot2触发chatgpt时附带文本内容

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#178]
### 描述

在群聊回复XDbot2触发chatgpt时附带上XDbot2发的文本内容（就是回复的那条）

### 原因

![image](https://user-images.githubusercontent.com/68174188/235358399-72b3d2c2-dcdc-4533-b27a-f1de4311018c.png)

**Comment by This-is-XiaoDeng** [comment]
如果时报错信息的话要改的有点多，毕竟下面那个消息是_error发的

如果也要回复可能要多加一个参数

**Comment by This-is-XiaoDeng** [comment]
gpt、chatgpt正常回复已经整上了

_error因为技术问题整不了放弃了.jpg

**Comment by xxtg666** [comment]
…？

**Comment by xxtg666** [comment]
我不是这个意思啊…我只是随手截了一张回复xdbot的图片

**Comment by xxtg666** [comment]
我指的是，在你回复xdbot消息的时候，吧xdbot发的那条消息作为ai说的话一并发给chatgpt

**Comment by This-is-XiaoDeng** [comment]
> 我指的是，在你回复xdbot消息的时候，吧xdbot发的那条消息作为ai说的话一并发给chatgpt

哦

**Comment by This-is-XiaoDeng** [comment]
这样？
