### ISSUE TITLE
[优化建议] 让cave-q能查看动图

### ISSUE THREAD

**Issue by YifanZhuZhu** [ITCraftDevelopmentTeam/XDbot2#193]
### 描述

如题

### 原因

cave-q不能查看动图

**Comment by This-is-XiaoDeng** [comment]
？

**Comment by This-is-XiaoDeng** [comment]
能给下复现步骤吗？

**Comment by This-is-XiaoDeng** [comment]
很抱歉，由于QQ在聊天框展示未缓存的图片/动图时只会显示一个静态预览图，XDbot2 目前无法处理这个问题

您可以使用 [Icalingua-Plus-Plus/](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus) 等第三方QQ临时解决这个问题
