### ISSUE TITLE
[新功能提案] Minecraft 新版本推送及最新版本查看

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#201]
### 描述

如题

**Comment by xxtg666** [comment]
实现逻辑很简单，本地写一个 `minecraft.version.txt` ，然后每隔一个小时检测 `https://launchermeta.mojang.com/mc/game/version_manifest.json` 中 `["versions"][0]["id"]` 是否和txt中的内容相同，如果不同就发送一个更新广播并且写入

**Comment by xxtg666** [comment]
# 好了，所以你自己写吧

**Comment by xxtg666** [comment]
更新提示的消息可以这样写：
```
发现MC更新：1.20-rc1(snapshot)
2023-06-01T12:24:09+00:00
```
