### ISSUE TITLE
[新功能提案] 添加物品：Mystery Box (⭐️)

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#209]
### 描述

使用后可随机获得若干经验、VimCoin 和一种少量商店物品（权重按价格倒序），并且可以在调用指令时随机掉落

后续还有 Mystery Box (⭐️⭐️⭐️) 和 Mystery Box (⭐️⭐️⭐️⭐️⭐️)，可以先不着急推出，等娱乐功能再发展下

### 原因

致敬 Hypixel

**Comment by muderstar** [comment]
会不会出现需要VIP,VIP+才可打开（

**Comment by muderstar** [comment]
还有个是给神秘碎片，宠物物品等

**Comment by muderstar** [comment]
有几率掉落神秘碎片（可以用来合成神秘箱(Mystery Box))
