### ISSUE TITLE
[新功能提案] 入群欢迎

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#219]
### 描述

如题

![图片](https://github.com/ITCraftDevelopmentTeam/XDbot2/assets/104149371/9eac407f-023a-4490-b549-475f73c302d6)

### 原因

致敬Sugar（x

![图片](https://github.com/ITCraftDevelopmentTeam/XDbot2/assets/104149371/817c80fe-d38b-4bcf-b59c-ff7703f11454)

**Comment by xxtg666** [comment]
```python
import httpx
async def getAcceptedQQList():
    async with httpx.AsyncClient() as client:
        r = (await client.get('https://api.github.com/repos/ITCraftDevelopmentTeam/Forum/issues/14/comments')).json()
        return [i['body'].replace("\n","") for i in r]
```
获取通过申请的QQ号列表
例: `["114514","1919810"]`

**Comment by This-is-XiaoDeng** [comment]
彳亍

**Comment by This-is-XiaoDeng** [comment]
> ```python
> import httpx
> async def getAcceptedQQList():
>     async with httpx.AsyncClient() as client:
>         r = (await client.get('https://api.github.com/repos/ITCraftDevelopmentTeam/Forum/issues/14/comments')).json()
>         return [i['body'].replace("\n","") for i in r]
> ```
> 
> 获取通过申请的QQ号列表 例: `["114514","1919810"]`

问题来了默认文本写什么（
