### ISSUE TITLE
[新功能提案] 添加物品：自动签到券

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#243]
### 描述

新增两个物品：自动签到券（激活）和自动签到券（未激活）
使用未激活的可以变成激活的，再使用一次变成未激活
每天23:50对所有用户触发：
如果用户当天未签到且背包中有自动签到券（激活），则消耗一个然后自动给他签到，并发个邮件提示
自动签到券可以通过二十面骰随机获取（直接获取到的是未激活）（不建议直接vi买，不然就无限刷了）

### 原因

我天天懒得签到

**Comment by This-is-XiaoDeng** [comment]
> 自动签到券可以通过二十面骰随机获取
（其实我想做到 #209 的 Mystery Box 里）

**Comment by xxtg666** [comment]
行，我没看见那个issue（

**Comment by This-is-XiaoDeng** [comment]
按计划来说本议题应该会被轮到 2.9 下半处理，请耐心等待<s>，或者发个pr</s>

**Comment by xxtg666** [comment]
> 按计划来说本议题应该会被轮到 2.9 下半处理，请耐心等待，或者发个pr

你上半才4个issue

**Comment by xxtg666** [comment]
https://github.com/ITCraftDevelopmentTeam/XDbot2/commit/3afddb5f18f75c91a1df732e36f4c9573bde49a1 https://github.com/ITCraftDevelopmentTeam/XDbot2/commit/863472abd41a62b3b68decbc47885c19a1230d90 https://github.com/ITCraftDevelopmentTeam/XDbot2/commit/6988018f1db76994101e1e639c8e7a4b8d13bb2a
已完成
