### ISSUE TITLE
[新功能提案] whoatme显示@消息的上下文

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#248]
### 描述

wam显示每条@消息时附带7条（上面7条、原文、下面7条）上下文（可用图片把15条消息整合进一条，或者合并转发套合并转发）

~~怎么记录下面7条你一定会写的吧~~

### 原因

只能看一条消息没啥用吧

**Comment by This-is-XiaoDeng** [comment]
（这么多 Issues 不知道要排到什么时候）

**Comment by xxtg666** [comment]
9

**Comment by This-is-XiaoDeng** [comment]
这个你放心，2.8下不知道，2.9上肯定会咕的

**Comment by This-is-XiaoDeng** [comment]
谢谢 @montmorill

**Comment by montmorill** [comment]
9，Maple全给你抄完了（半恼

**Comment by This-is-XiaoDeng** [comment]
> 9，Maple全给你抄完了（半恼

XDbot也快给你抄完了好不好！！！

**Comment by montmorill** [comment]
> > 9，Maple全给你抄完了（半恼
> 
> XDbot也快给你抄完了好不好！！！

一起抄Sugar去（bushi
