### ISSUE TITLE
[优化建议] 调整cave冷却时间及一些修改

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#315]
### 描述

- 将cave冷却时间上调至 *1小时*
- 为cave添加随机的 *vi、经验奖励*

### 原因

现在的cave并没有起到任何的活跃群聊气氛的作用

反倒是有些人<sup>说的就是你，@YifanZhuZhu</sup>无聊的时候用cave**刷屏**

所以建议像PCL群一样，将冷却时间调至1小时，这样到了时间说不定就会有人刷cave<sup>同时获得vi奖励</sup>

<sub>~~本来是想了一大堆理由的发现不会写（~~</sub>

**Comment by This-is-XiaoDeng** [comment]
1h，优点久（

~~我自己还要刷呢~~

**Comment by This-is-XiaoDeng** [comment]
我想的是可以学一下Sugar，普通群半小时，用户群10分钟，同时记录每条cave被刷出来的次数构成优先级，避免真随机出太多重复

**Comment by xxtg666** [comment]
> 1h，优点久（
> 
> ~我自己还要刷呢~

时间调这么长和添加奖励得目的就是为了活跃群聊的（
如果间隔时间太短，刷多了就没意思了

**Comment by xxtg666** [comment]
> 我想的是可以学一下Sugar（指给用户群特惠），普通群半小时，用户群10分钟，同时记录每条cave被刷出来的次数构成优先级，避免真随机出太多重复

优先级不需要，反正已经几千条了

**Comment by YifanZhuZhu** [comment]
？

**Comment by YifanZhuZhu** [comment]
草

**Comment by YifanZhuZhu** [comment]
how grass this issue is

**Comment by This-is-XiaoDeng** [comment]
好
