### ISSUE TITLE
[优化建议] 自动精华添加分群添加关键词及模糊匹配功能

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#354]
### 描述

在自动精华添加分群添加关键词，允许群管及SUPERUSER（`GROUP_OWNER | GROUP_ADMIN | SUPERUSER`，前两个在`nonebot.adapter.onebot.v11.permission`）设置各群自动精华关键词，同时添加模糊匹配，匹配文本相似度，遇到相似文本自动精华

**Comment by montmorill** [comment]
模糊匹配，匹配文本相似度是吧

**Comment by This-is-XiaoDeng** [comment]
> 模糊匹配，匹配文本相似度是吧

是（

**Comment by This-is-XiaoDeng** [comment]
这个插件已经被删除了
