### ISSUE TITLE
[Bug 反馈] 今日人品在07:52刷新

### ISSUE THREAD

**Issue by catmeowjiao** [ITCraftDevelopmentTeam/XDbot2#398]
### 描述

今日人品在07:52刷新

### 重现步骤

1.07:51和07:53调用jrrp
2.看代码, 应为random.seed(int(qq) + int((time.time() + 28800) / 86400))而不是random.seed(int(qq) + int((time.time() + 480) / 86400))

### 截图

无

**Comment by chun-awa** [comment]
xd：摆烂（
