### ISSUE TITLE
[Bug 反馈] sudo 时 event.sender 获取到的仍然是原发送者的信息

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#424]
### 描述

使用`/sudo`指令时，`event.sender`获取到的仍然是`/sudo`指令发送者的信息，而不是指定用户的信息

### 重现步骤

/sudo 1744793737 /qm-p

### 截图

![Screenshot_20230902_231942](https://github.com/ITCraftDevelopmentTeam/XDbot2/assets/104149371/a513588e-afff-43db-b5e4-8c9eba572ed4)

> 预期情况下上图中`XTBot`应为`xɪᴀᴏᴅᴇɴɢ3386`

**Comment by XieXiLin2** [comment]
评价:
那么 sender 还有 card 和 age 参，这些需要替换掉么🤔

**Comment by This-is-XiaoDeng** [comment]
是的

**Comment by XieXiLin2** [comment]
那更麻烦了😨

**Comment by This-is-XiaoDeng** [comment]
直接`bot.get_stranger_info`不行吗（？

**Comment by XieXiLin2** [comment]
🤔那不是花的时间更长了吗

**Comment by This-is-XiaoDeng** [comment]
或许也可以在`.env`中放个开关，默认关闭

**Comment by XieXiLin2** [comment]
good🤔那就这么干别（）
