### ISSUE TITLE
[新功能提案] 化学反应模拟器

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#466]
### 描述

来自 [This-is-XiaoDeng/XDbot](https://github.com/This-is-XiaoDeng/XDbot#todo)

> @xxtg666 来补充下

其他的不是很清楚，只知道有个 `ba+2na===banana`，xxtg 提的

**Comment by muderstar** [comment]
co+fe2=coffee
化学反应方程式(X)
单词组成器（V）
