### ISSUE TITLE
[新功能提案] 允许自定义调教条目对群聊或用户的触发概率

### ISSUE THREAD

**Issue by DQB061204** [ITCraftDevelopmentTeam/XDbot2#467]
### 描述

可以给xdbot检测的时候增加朴素贝叶斯分类器的分词功能 以减少在利用调教功能时对于调教功能无关的词汇的反馈

### 原因

减少不必要的伤害 例如：一个人说：我要寄了 然后xdbot说：六字真言？在我这不管用！ 有可能增加群友自残等的风险

**Comment by This-is-XiaoDeng** [comment]
根据「描述」的信息，增加一个「朴素贝叶斯分类器」的筛选模式，恐怕难以达到「原因」中「减少不必要的伤害 」 的效果。

如果要检测发送者的可能的心理活动，这需要的数据量是十分庞大的。显然，我们没办法获得那么多的数据，也没有办法训练一个这样的模型。

**Comment by DQB061204** [comment]
就是减少反馈次数 两个选项 一个是50%概率发送 一个是增加分词功能 使其不要那么敏感

**Comment by DQB061204** [comment]
*选其一即可

**Comment by This-is-XiaoDeng** [comment]
你在让我选还是让用户选.jpg

**Comment by This-is-XiaoDeng** [comment]
或者是让用户自己开

**Comment by DQB061204** [comment]
让你选
