### ISSUE TITLE
[加入新群] 

### ISSUE THREAD

**Issue by bowen99** [ITCraftDevelopmentTeam/XDbot2#640]
### 开始之前……

- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ号

1106308976

### QQ群

895337184

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by This-is-XiaoDeng** [comment]
XDbot2 已向此群发送加群申请，节点代码为 `0x01`
