### ISSUE TITLE
[优化建议] 回声洞内容仅存在图片时不进行文本审核

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#641]
### 描述

用户提交回声洞时，如果提交的内容仅存在图片，就不进行文本审核

### 原因

![image](https://github.com/ITCraftDevelopmentTeam/XDbot2/assets/68174188/1e33f3ec-440d-4c3c-b59b-39c62886cfb1)
……这不是资源浪费么？

**Comment by This-is-XiaoDeng** [comment]
这不是你写的么（x

**Comment by xxtg666** [comment]
写的时候忘记了，现在提一下（
