### ISSUE TITLE
[优化建议] 在展示 FTT 结果发送模拟运行图

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [ITCraftDevelopmentTeam/XDbot2#653]
### 描述

在 FTT 发送结果（成功、失败）、退出 时，附带模拟运行结果

https://github.com/xxtg666/XDbot2FTTsolver/blob/main/ftt_solver.py#L86

**Comment by xxtg666** [comment]
我提醒一下，我写的这个是修改了寻路的模块，在寻路过程中就记录信息并直接使用这些信息作图，而不是根据已经给出的地图和解法作图，所以可能有点难搬上去（

**Comment by This-is-XiaoDeng** [comment]
> 我提醒一下，我写的这个是修改了寻路的模块，在寻路过程中就记录信息并直接使用这些信息作图，而不是根据已经给出的地图和解法作图，所以可能有点难搬上去（

我直接复制相关的过去不就完了

**Comment by xxtg666** [comment]
> 我直接复制相关的过去不就完了

那你更新 FTT 的时候我这也能同步更新了对吧（）

**Comment by This-is-XiaoDeng** [comment]
5
