### ISSUE TITLE
[新功能提案] 回复初始提交回声洞的消息时添加评论

### ISSUE THREAD

**Issue by xxtg666** [ITCraftDevelopmentTeam/XDbot2#666]
### 描述

在用户提交回声洞的时候，允许直接回复用户的消息以添加回声洞评论，而不是需要等刷出来再回复才能添加。

### 原因

在当前的操作流程中，用户在提交到回声洞的消息后，其他用户想要对这些消息进行评论，必须等待这些消息在回声洞中随机刷新出现后，才能进行评论。这种设计使得在第一时间对消息进行评论变得不可能，因为回声洞的刷新机制是随机的。

~~我也不知道这个功能能不能做，看上去有性能影响（~~

**Comment by This-is-XiaoDeng** [comment]
影响不大其实， ~~毕竟 `-a` 已经够慢了（捂脸）~~
