### ISSUE TITLE
[新功能提案] something about bag

### ISSUE THREAD

**Issue by YifanZhuZhu** [ITCraftDevelopmentTeam/XDbot2#670]
### 描述

/bag limit [num]:背包上限增加num,与此同时消耗num*512vim.
/bag reset:背包上限恢复，同时清空物品

**Comment by This-is-XiaoDeng** [comment]
先把 32 組上線玩滿再說吧

**Comment by This-is-XiaoDeng** [comment]
你這個疑似和 https://github.com/ITCraftDevelopmentTeam/XDbot2/issues/269 有點像（
