### ISSUE TITLE
[加入新群] 

### ISSUE THREAD

**Issue by ghost** [ITCraftDevelopmentTeam/XDbot2#692]
### 开始之前……

- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ号

479571968

### QQ群

671632461

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by This-is-XiaoDeng** [comment]
等我下午考完再处理

**Comment by This-is-XiaoDeng** [comment]
已发送加群请求
